### PR TITLE
Create README-FR.md

### PR DESCRIPTION
**Pull request by omar6260**
# 1. Description

## 1.1. Checklist

- [ ] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [ ] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## 1.2. Breaking Change

- [ ] Yes, this is a breaking change.
- [ ] No, this is _not_ a breaking change.

## 1.3. Related Issues

[issue database]: https://github.com/twitter-dart/twitter-api-v2/issues
[contributor guide]: https://github.com/twitter-dart/twitter-api-v2/blob/main/CONTRIBUTING.md
[style guide]: https://github.com/twitter-dart/twitter-api-v2/blob/main/STYLEGUIDE.md
[conventional commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by myConsciousness** [comment]
Hi @omar6260 , thanks for your contribution but I can't see translation for Frente yet, can you commit more? :)

**Comment by omar6260** [comment]
Hello @myConsciousness yes, it's true yesterday i had a Hitch that's why i didn't finish the contribution

**Comment by myConsciousness** [comment]
Hi @omar6260 , that's okay I'll be waiting for your commitments! 😁👍

**Comment by myConsciousness** [comment]
Close and merge #242

**Pull request closed without merging**
