### PR TITLE
fix: Fixing API use for reply_settings and reply

### PR DESCRIPTION
**Pull request by XRayAdamo**
# 1. Description

It seems that Twitter API does not allow 
reply to be empty so it should not be included into body or POST will fail
Same goes for reply_settings field. It cannot be empty and somehow should not "everyone". Only if value = mentionedUsers or following then it should be included into body.

Looks like a bug of twitter API or a limitation, but documentation on API does not tell you this.

## 1.1. Checklist

- [ X] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [ X] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples`.

## 1.2. Breaking Change

- [ ] Yes, this is a breaking change.
- [X ] No, this is _not_ a breaking change.

## 1.3. Related Issues

[issue database]: https://github.com/twitter-dart/twitter-api-v2/issues
[contributor guide]: https://github.com/twitter-dart/twitter-api-v2/blob/main/CONTRIBUTING.md
[style guide]: https://github.com/twitter-dart/twitter-api-v2/blob/main/STYLEGUIDE.md
[conventional commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by XRayAdamo** [comment]
Here is test request with empty string
image

same for everyone value
image

and same for in_reply_to
image

**Comment by myConsciousness** [comment]
> Here is test request with empty string image
> 
> same for everyone value image
> 
> and same for in_reply_to image

Reading from this response, isn't `everyone` in the Enum necessary in the first place? 🤔

**Comment by XRayAdamo** [comment]
If everyone value is not going to be used in other GET API calls, it can be removed.
But if you are planing to support this field in GET calls , you can leave it.
Like in this one
https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets

image

It is strange that API returns everyone but does not accept it.

**Comment by myConsciousness** [comment]
> If everyone value is not going to be used in other GET API calls, it can be removed. But if you are planing to support this field in GET calls , you can leave it. Like in this one https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets
> 
> image
> 
> It is strange that API returns everyone but does not accept it.

I see, so `everyone` may be returned as a response 🤔

Hmm it would just be similar to the empty string validate, but I think the error returned by the API would be meaningful.

In other words, it's quite possible that an implementor may not pass a valid value as an argument to a method in this library, but in the end it will only make a difference whether it is checked by this library or by the API.  From another perspective, if we were to include this check process, it would be a proprietary specification of this library.

From another perspective, I feel that sending an unsupported value during POST **should** naturally result in an error and is something that implementors using this library should be aware when calling `createTweet` 🤔

It's very difficult choice, but considering the above, I do not see the point in adding these checks at this time :)

**Comment by XRayAdamo** [comment]
Those checks will ignore adding fields into body if they are empty/null. You mentioned cleaning process to eliminate nulls. Correct me if I am wrong, but you want to first add everything into dictionary and after that clean null fields, right? This will work in situation like in_replay_to field, but for reply_settings it requires additional  checking for “everyone” value. If we remove this enum entry then it could work.

**Comment by myConsciousness** [comment]
Yes @XRayAdamo , that is correct understanding :) 

I just don't understand the use case of explicitly passing the value `everyone` which cannot be used in Twitter API when executing `createTweet` in the first place 🤔 

I mean, if we were to check input, the following would be better than ignoring errors from Twitter API:

```dart
if (replySetting == ReplySetting.everyone) {
    throw ArgumentError();
}
```

However, this is merely a reimplementation of the Twitter API's internal validation. Rather, I think it would be better to add a note to dartdoc that `everyone` in `ReplySetting` cannot be used for tweet endpoint 🤔

Or is there a use case where this `everyone` check is absolutely necessary?

**Comment by myConsciousness** [comment]
It's very difficult issue haha.

Well, I don't want to implement special specifications in this library that differ from the Twitter API specifications as much as possible. Yes, `everyone` in `ReplySetting` is confusing one, but I don't think it is necessary to ignore `everyone` in createTweet unless there is a use case where it would interfere with the processing.

**Comment by XRayAdamo** [comment]
How about separate functions with different parameters? The one with reply_settings will accept non null value and let API to report error if user passes “everyone”

**Comment by myConsciousness** [comment]
Okay @XRayAdamo , I have sorted out and will agree your idea! However, please let me fix it like this later :)

```dart
      body: {
        'text': text,
        'quote_tweet_id': quoteTweetId,
        'for_super_followers_only': forSuperFollowersOnly,
        'reply': {
          'in_reply_to_tweet_id': inReplyToTweetId,
        },
        'reply_settings':
            replySetting != ReplySetting.everyone ? replySetting?.name : null,
      },
```

**Review by myConsciousness — APPROVED** [review]

**Comment by myConsciousness** [comment]
bors merge

**Pull request merged**
